services:
  # web:
  #   build: .
  #   restart: always
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - db
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: abdallahbedir
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: movies
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql:
